-- GENERATED by @lyku/lockstep-sqlite from server/models/db.ts — do not edit by hand.
-- Regenerate: bun server/models/generate.ts
-- Apply:      wrangler d1 execute parascape --remote --file=schema.sql

--------------------------------
----------  users  ----------
--------------------------------

---- Create table
CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "username" TEXT CHECK (length("username") >= 3) UNIQUE NOT NULL, "password_hash" TEXT NOT NULL, "created_at" INTEGER NOT NULL);


--------------------------------
---------  sessions  ---------
--------------------------------

---- Create table
CREATE TABLE IF NOT EXISTS "sessions" ("token" TEXT PRIMARY KEY, "user_id" INTEGER NOT NULL, "created_at" INTEGER NOT NULL);

---- Create indexes
CREATE INDEX IF NOT EXISTS "idx_sessions_user_id" ON "sessions" ("user_id");


--------------------------------
---------  projects  ---------
--------------------------------

---- Create table
CREATE TABLE IF NOT EXISTS "projects" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "user_id" INTEGER NOT NULL, "name" TEXT NOT NULL, "doc" TEXT NOT NULL, "updated_at" INTEGER NOT NULL);

---- Create indexes
CREATE INDEX IF NOT EXISTS "idx_projects_user_id" ON "projects" ("user_id");


--------------------------------
----------  assets  ----------
--------------------------------

---- Create table
CREATE TABLE IF NOT EXISTS "assets" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "user_id" INTEGER NOT NULL, "name" TEXT NOT NULL, "mime" TEXT NOT NULL, "size" INTEGER NOT NULL, "data" BLOB NOT NULL, "created_at" INTEGER NOT NULL);

---- Create indexes
CREATE INDEX IF NOT EXISTS "idx_assets_user_id" ON "assets" ("user_id");


--------------------------------
--------  published  --------
--------------------------------

---- Create table
CREATE TABLE IF NOT EXISTS "published" ("slug" TEXT PRIMARY KEY, "user_id" INTEGER NOT NULL, "doc" TEXT NOT NULL, "updated_at" INTEGER NOT NULL);


--------------------------------
--------  snapshots  --------
--------------------------------

---- Create table
CREATE TABLE IF NOT EXISTS "snapshots" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "user_id" INTEGER NOT NULL, "label" TEXT NOT NULL, "doc" TEXT NOT NULL, "created_at" INTEGER NOT NULL);

---- Create indexes
CREATE INDEX IF NOT EXISTS "idx_snapshots_user_id" ON "snapshots" ("user_id");

