// Regenerate everything lockstep derives from the Parascape models:
//
//   bun server/models/generate.ts
//
//   • schema.sql              ← @lyku/lockstep-sqlite  (apply to D1)
//   • generated/json-models   ← record types + TSON schemas (db.ts)
//   • generated/db-types      ← Kysely Database interface (db.ts)
//   • generated/api-types     ← request/response types (api.ts)
//   • generated/handles       ← server handler factories (api.ts)
//   • generated/client        ← typed browser API client (api.ts)
//
// Apply the schema: wrangler d1 execute parascape --remote --file=schema.sql
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { generateCreateTablesSql } from "@lyku/lockstep-sqlite";
import { generateJsonModels, generateApiTypes, generateHandles, generateClient } from "@lyku/lockstep-core/generators";
import * as db from "./db";
import * as api from "./api";

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));
const root = here("../../"); // Parascape repo root
const gen = (p: string) => `${root}server/generated/${p}`;

// ── 1. SQLite schema ──
const header = [
  "-- GENERATED by @lyku/lockstep-sqlite from server/models/db.ts — do not edit by hand.",
  "-- Regenerate: bun server/models/generate.ts",
  "-- Apply:      wrangler d1 execute parascape --remote --file=schema.sql",
  "",
  "",
].join("\n");
writeFileSync(`${root}schema.sql`, header + generateCreateTablesSql(db.config as never));
console.log("✓ schema.sql");

// ── 2. record types (Worker uses raw D1, so no Kysely db-types) ──
await generateJsonModels({ models: db.records, outputDir: gen("json-models") } as never);
console.log("✓ json-models");

// ── 3. API request/response types ──
await generateApiTypes({ models: api as Record<string, unknown>, outputDir: gen("api-types") });
console.log("✓ api-types");

// ── 4. server handler factories ──
// The generated handle JS imports the model objects from `modelsPackage` and
// the request/response types from `typesPackage`; both are local relative
// imports (esbuild/wrangler resolve them at Worker bundle time).
await generateHandles({
  models: api as Record<string, unknown>,
  outputDir: gen("handles"),
  modelsPackage: "../../models/api",
  typesPackage: "../api-types",
});
console.log("✓ handles");

// ── 5. typed browser client ──
await generateClient({
  models: api as Record<string, unknown>,
  name: "Parascape",
  outputDir: gen("client"),
  typesPackage: "../api-types",
} as never);
console.log("✓ client");

console.log("\nAll generated → server/generated/");
