// AUTO-GENERATED by scripts/gen-sibits-manifest.ts — do not edit by hand.
// Source: @lyku/si-bits (303 components).
import type { CatalogGroup, CatalogItem } from "../catalog";

export const catalog: CatalogGroup[] = [
  {
    category: "si-bits",
    items: [
          {
                "name": "AccessibilitySettings",
                "id": "accessibility-settings",
                "blurb": ""
          },
          {
                "name": "AccountSwitcher",
                "id": "account-switcher",
                "blurb": ""
          },
          {
                "name": "AchievementList",
                "id": "achievement-list",
                "blurb": ""
          },
          {
                "name": "AdBanner",
                "id": "ad-banner",
                "blurb": ""
          },
          {
                "name": "AdCampaignManager",
                "id": "ad-campaign-manager",
                "blurb": ""
          },
          {
                "name": "AddToPlaylistModal",
                "id": "add-to-playlist-modal",
                "blurb": ""
          },
          {
                "name": "AdPreferences",
                "id": "ad-preferences",
                "blurb": ""
          },
          {
                "name": "Aerial",
                "id": "aerial",
                "blurb": ""
          },
          {
                "name": "Agreeable",
                "id": "agreeable",
                "blurb": ""
          },
          {
                "name": "AltTextEditor",
                "id": "alt-text-editor",
                "blurb": ""
          },
          {
                "name": "AmbientEffects",
                "id": "ambient-effects",
                "blurb": ""
          },
          {
                "name": "AnalyticsBarChart",
                "id": "analytics-bar-chart",
                "blurb": ""
          },
          {
                "name": "AnalyticsDashboard",
                "id": "analytics-dashboard",
                "blurb": ""
          },
          {
                "name": "AnalyticsHeatmap",
                "id": "analytics-heatmap",
                "blurb": ""
          },
          {
                "name": "AnalyticsLineChart",
                "id": "analytics-line-chart",
                "blurb": ""
          },
          {
                "name": "AnalyticsMetricCard",
                "id": "analytics-metric-card",
                "blurb": ""
          },
          {
                "name": "AnalyticsPeriodSelector",
                "id": "analytics-period-selector",
                "blurb": ""
          },
          {
                "name": "ApiKeyManager",
                "id": "api-key-manager",
                "blurb": ""
          },
          {
                "name": "AppDirectory",
                "id": "app-directory",
                "blurb": ""
          },
          {
                "name": "AppEmbed",
                "id": "app-embed",
                "blurb": ""
          },
          {
                "name": "Ascendere",
                "id": "ascendere",
                "blurb": ""
          },
          {
                "name": "AttachmentEditor",
                "id": "attachment-editor",
                "blurb": ""
          },
          {
                "name": "AudienceBreakdown",
                "id": "audience-breakdown",
                "blurb": ""
          },
          {
                "name": "AuthorCard",
                "id": "author-card",
                "blurb": ""
          },
          {
                "name": "Backdrop",
                "id": "backdrop",
                "blurb": ""
          },
          {
                "name": "BadgePopover",
                "id": "badge-popover",
                "blurb": ""
          },
          {
                "name": "Banner",
                "id": "banner",
                "blurb": ""
          },
          {
                "name": "BefriendUser",
                "id": "befriend-user",
                "blurb": ""
          },
          {
                "name": "BotCommandList",
                "id": "bot-command-list",
                "blurb": ""
          },
          {
                "name": "BotListWithCreator",
                "id": "bot-list-with-creator",
                "blurb": ""
          },
          {
                "name": "BotManager",
                "id": "bot-manager",
                "blurb": ""
          },
          {
                "name": "Button",
                "id": "button",
                "blurb": ""
          },
          {
                "name": "CallInProgressBanner",
                "id": "call-in-progress-banner",
                "blurb": ""
          },
          {
                "name": "CaptionOverlay",
                "id": "caption-overlay",
                "blurb": ""
          },
          {
                "name": "Card",
                "id": "card",
                "blurb": ""
          },
          {
                "name": "Cards",
                "id": "cards",
                "blurb": ""
          },
          {
                "name": "CardSelector",
                "id": "card-selector",
                "blurb": ""
          },
          {
                "name": "Center",
                "id": "center",
                "blurb": ""
          },
          {
                "name": "Channel",
                "id": "channel",
                "blurb": ""
          },
          {
                "name": "ChannelList",
                "id": "channel-list",
                "blurb": ""
          },
          {
                "name": "ChannelListWithCreator",
                "id": "channel-list-with-creator",
                "blurb": ""
          },
          {
                "name": "ChannelLogo",
                "id": "channel-logo",
                "blurb": ""
          },
          {
                "name": "ChatBox",
                "id": "chat-box",
                "blurb": ""
          },
          {
                "name": "ChatList",
                "id": "chat-list",
                "blurb": ""
          },
          {
                "name": "ChatListSkeleton",
                "id": "chat-list-skeleton",
                "blurb": ""
          },
          {
                "name": "ChatPollMessage",
                "id": "chat-poll-message",
                "blurb": ""
          },
          {
                "name": "ChatPopup",
                "id": "chat-popup",
                "blurb": ""
          },
          {
                "name": "ChatSearch",
                "id": "chat-search",
                "blurb": ""
          },
          {
                "name": "ChatView",
                "id": "chat-view",
                "blurb": ""
          },
          {
                "name": "Checkbox",
                "id": "checkbox",
                "blurb": ""
          },
          {
                "name": "ChunkViz",
                "id": "chunk-viz",
                "blurb": ""
          },
          {
                "name": "ClipCreator",
                "id": "clip-creator",
                "blurb": ""
          },
          {
                "name": "ClipPlayer",
                "id": "clip-player",
                "blurb": ""
          },
          {
                "name": "Close",
                "id": "close",
                "blurb": ""
          },
          {
                "name": "CoAuthorBadge",
                "id": "co-author-badge",
                "blurb": ""
          },
          {
                "name": "Codette",
                "id": "codette",
                "blurb": ""
          },
          {
                "name": "CollaborativeEditor",
                "id": "collaborative-editor",
                "blurb": ""
          },
          {
                "name": "CollaborativePlaylist",
                "id": "collaborative-playlist",
                "blurb": ""
          },
          {
                "name": "CollaboratorList",
                "id": "collaborator-list",
                "blurb": ""
          },
          {
                "name": "CommandPalette",
                "id": "command-palette",
                "blurb": ""
          },
          {
                "name": "ConstellationField",
                "id": "constellation-field",
                "blurb": ""
          },
          {
                "name": "ContentPerformanceTable",
                "id": "content-performance-table",
                "blurb": ""
          },
          {
                "name": "ContentWarningOverlay",
                "id": "content-warning-overlay",
                "blurb": ""
          },
          {
                "name": "ContentWarningPicker",
                "id": "content-warning-picker",
                "blurb": ""
          },
          {
                "name": "ContentWarningSettings",
                "id": "content-warning-settings",
                "blurb": ""
          },
          {
                "name": "ContentWarningTag",
                "id": "content-warning-tag",
                "blurb": ""
          },
          {
                "name": "CosmicBackground",
                "id": "cosmic-background",
                "blurb": ""
          },
          {
                "name": "CoStreamPanel",
                "id": "co-stream-panel",
                "blurb": ""
          },
          {
                "name": "CreateChatDialog",
                "id": "create-chat-dialog",
                "blurb": ""
          },
          {
                "name": "CreateGroupDialog",
                "id": "create-group-dialog",
                "blurb": ""
          },
          {
                "name": "CreatorDashboard",
                "id": "creator-dashboard",
                "blurb": ""
          },
          {
                "name": "CreatorEarningsDashboard",
                "id": "creator-earnings-dashboard",
                "blurb": ""
          },
          {
                "name": "CrossdrawEmbed",
                "id": "crossdraw-embed",
                "blurb": ""
          },
          {
                "name": "Crosshatch",
                "id": "crosshatch",
                "blurb": ""
          },
          {
                "name": "CustomFeedBuilder",
                "id": "custom-feed-builder",
                "blurb": ""
          },
          {
                "name": "DesktopNav",
                "id": "desktop-nav",
                "blurb": ""
          },
          {
                "name": "Dialog",
                "id": "dialog",
                "blurb": ""
          },
          {
                "name": "Disable2FADialog",
                "id": "disable2-fa-dialog",
                "blurb": ""
          },
          {
                "name": "DiscoveryFeed",
                "id": "discovery-feed",
                "blurb": ""
          },
          {
                "name": "Divisio",
                "id": "divisio",
                "blurb": ""
          },
          {
                "name": "DraftList",
                "id": "draft-list",
                "blurb": ""
          },
          {
                "name": "Dropdown",
                "id": "dropdown",
                "blurb": ""
          },
          {
                "name": "DynamicDate",
                "id": "dynamic-date",
                "blurb": ""
          },
          {
                "name": "DynamicPost",
                "id": "dynamic-post",
                "blurb": ""
          },
          {
                "name": "EarlyAccessSignup",
                "id": "early-access-signup",
                "blurb": ""
          },
          {
                "name": "EmbedCreator",
                "id": "embed-creator",
                "blurb": ""
          },
          {
                "name": "EmbeddedPost",
                "id": "embedded-post",
                "blurb": ""
          },
          {
                "name": "EmojiManager",
                "id": "emoji-manager",
                "blurb": ""
          },
          {
                "name": "Empty",
                "id": "empty",
                "blurb": ""
          },
          {
                "name": "EventCalendar",
                "id": "event-calendar",
                "blurb": ""
          },
          {
                "name": "EventCard",
                "id": "event-card",
                "blurb": ""
          },
          {
                "name": "EventDetail",
                "id": "event-detail",
                "blurb": ""
          },
          {
                "name": "EventForm",
                "id": "event-form",
                "blurb": ""
          },
          {
                "name": "EventList",
                "id": "event-list",
                "blurb": ""
          },
          {
                "name": "ExploreGrid",
                "id": "explore-grid",
                "blurb": ""
          },
          {
                "name": "ExplorePage",
                "id": "explore-page",
                "blurb": ""
          },
          {
                "name": "ExploreSearch",
                "id": "explore-search",
                "blurb": ""
          },
          {
                "name": "ExploreSectionCard",
                "id": "explore-section-card",
                "blurb": ""
          },
          {
                "name": "FamilyLinkSetup",
                "id": "family-link-setup",
                "blurb": ""
          },
          {
                "name": "FeedPage",
                "id": "feed-page",
                "blurb": ""
          },
          {
                "name": "FeedTabs",
                "id": "feed-tabs",
                "blurb": ""
          },
          {
                "name": "Fof",
                "id": "fof",
                "blurb": ""
          },
          {
                "name": "FollowUser",
                "id": "follow-user",
                "blurb": ""
          },
          {
                "name": "Footer",
                "id": "footer",
                "blurb": ""
          },
          {
                "name": "ForumCategoryList",
                "id": "forum-category-list",
                "blurb": ""
          },
          {
                "name": "ForumReplyComposer",
                "id": "forum-reply-composer",
                "blurb": ""
          },
          {
                "name": "ForumSearch",
                "id": "forum-search",
                "blurb": ""
          },
          {
                "name": "ForumThreadList",
                "id": "forum-thread-list",
                "blurb": ""
          },
          {
                "name": "ForumThreadView",
                "id": "forum-thread-view",
                "blurb": ""
          },
          {
                "name": "ForYouFeed",
                "id": "for-you-feed",
                "blurb": ""
          },
          {
                "name": "FriendInviter",
                "id": "friend-inviter",
                "blurb": ""
          },
          {
                "name": "GifPicker",
                "id": "gif-picker",
                "blurb": ""
          },
          {
                "name": "GiftSubButton",
                "id": "gift-sub-button",
                "blurb": ""
          },
          {
                "name": "GroupAiSettings",
                "id": "group-ai-settings",
                "blurb": ""
          },
          {
                "name": "GroupChatList",
                "id": "group-chat-list",
                "blurb": ""
          },
          {
                "name": "GroupFilterSelect",
                "id": "group-filter-select",
                "blurb": ""
          },
          {
                "name": "GroupIcon",
                "id": "group-icon",
                "blurb": ""
          },
          {
                "name": "GroupList",
                "id": "group-list",
                "blurb": ""
          },
          {
                "name": "HashtagFollowButton",
                "id": "hashtag-follow-button",
                "blurb": ""
          },
          {
                "name": "HologramBubble",
                "id": "hologram-bubble",
                "blurb": ""
          },
          {
                "name": "Image",
                "id": "image",
                "blurb": ""
          },
          {
                "name": "ImageEditor",
                "id": "image-editor",
                "blurb": ""
          },
          {
                "name": "ImageUpload",
                "id": "image-upload",
                "blurb": ""
          },
          {
                "name": "InteractionTracker",
                "id": "interaction-tracker",
                "blurb": ""
          },
          {
                "name": "KeybindPalette",
                "id": "keybind-palette",
                "blurb": ""
          },
          {
                "name": "KeybindProvider",
                "id": "keybind-provider",
                "blurb": ""
          },
          {
                "name": "KeybindSettings",
                "id": "keybind-settings",
                "blurb": ""
          },
          {
                "name": "KeybindsHelp",
                "id": "keybinds-help",
                "blurb": ""
          },
          {
                "name": "LayoutToggle",
                "id": "layout-toggle",
                "blurb": ""
          },
          {
                "name": "LeaderboardTable",
                "id": "leaderboard-table",
                "blurb": ""
          },
          {
                "name": "LeftAlign",
                "id": "left-align",
                "blurb": ""
          },
          {
                "name": "LevelBadge",
                "id": "level-badge",
                "blurb": ""
          },
          {
                "name": "LevelPopover",
                "id": "level-popover",
                "blurb": ""
          },
          {
                "name": "LevelUpOverlay",
                "id": "level-up-overlay",
                "blurb": ""
          },
          {
                "name": "Lightbox",
                "id": "lightbox",
                "blurb": ""
          },
          {
                "name": "Link",
                "id": "link",
                "blurb": ""
          },
          {
                "name": "LinkPreview",
                "id": "link-preview",
                "blurb": ""
          },
          {
                "name": "ListingCard",
                "id": "listing-card",
                "blurb": ""
          },
          {
                "name": "ListingDetail",
                "id": "listing-detail",
                "blurb": ""
          },
          {
                "name": "ListingForm",
                "id": "listing-form",
                "blurb": ""
          },
          {
                "name": "LiveBadge",
                "id": "live-badge",
                "blurb": ""
          },
          {
                "name": "LivePlayer",
                "id": "live-player",
                "blurb": ""
          },
          {
                "name": "LiveStreamCard",
                "id": "live-stream-card",
                "blurb": ""
          },
          {
                "name": "Loading",
                "id": "loading",
                "blurb": ""
          },
          {
                "name": "LoadingOverlay",
                "id": "loading-overlay",
                "blurb": ""
          },
          {
                "name": "Logo",
                "id": "logo",
                "blurb": ""
          },
          {
                "name": "LostPlotGame",
                "id": "lost-plot-game",
                "blurb": ""
          },
          {
                "name": "MapLibreViewer",
                "id": "map-libre-viewer",
                "blurb": ""
          },
          {
                "name": "MapSearch",
                "id": "map-search",
                "blurb": ""
          },
          {
                "name": "MarketplaceSearch",
                "id": "marketplace-search",
                "blurb": ""
          },
          {
                "name": "MatchInfo",
                "id": "match-info",
                "blurb": ""
          },
          {
                "name": "MatchList",
                "id": "match-list",
                "blurb": ""
          },
          {
                "name": "MatchProposalList",
                "id": "match-proposal-list",
                "blurb": ""
          },
          {
                "name": "MediaRecorder",
                "id": "media-recorder",
                "blurb": ""
          },
          {
                "name": "MessageComposer",
                "id": "message-composer",
                "blurb": ""
          },
          {
                "name": "MessageItem",
                "id": "message-item",
                "blurb": ""
          },
          {
                "name": "MessagingDropdown",
                "id": "messaging-dropdown",
                "blurb": ""
          },
          {
                "name": "MobileNav",
                "id": "mobile-nav",
                "blurb": ""
          },
          {
                "name": "ModerationAppeal",
                "id": "moderation-appeal",
                "blurb": ""
          },
          {
                "name": "ModerationDashboard",
                "id": "moderation-dashboard",
                "blurb": ""
          },
          {
                "name": "ModerationQueue",
                "id": "moderation-queue",
                "blurb": ""
          },
          {
                "name": "MoreFromAuthor",
                "id": "more-from-author",
                "blurb": ""
          },
          {
                "name": "NativeAd",
                "id": "native-ad",
                "blurb": ""
          },
          {
                "name": "NavLogo",
                "id": "nav-logo",
                "blurb": ""
          },
          {
                "name": "NewChatView",
                "id": "new-chat-view",
                "blurb": ""
          },
          {
                "name": "NexusHub",
                "id": "nexus-hub",
                "blurb": ""
          },
          {
                "name": "NexusShell",
                "id": "nexus-shell",
                "blurb": ""
          },
          {
                "name": "NexusZone",
                "id": "nexus-zone",
                "blurb": ""
          },
          {
                "name": "NotificationDropdown",
                "id": "notification-dropdown",
                "blurb": ""
          },
          {
                "name": "NotificationOverlay",
                "id": "notification-overlay",
                "blurb": ""
          },
          {
                "name": "NotificationPreferences",
                "id": "notification-preferences",
                "blurb": ""
          },
          {
                "name": "NotificationSettings",
                "id": "notification-settings",
                "blurb": ""
          },
          {
                "name": "NotificationsPage",
                "id": "notifications-page",
                "blurb": ""
          },
          {
                "name": "OAuthAppManager",
                "id": "o-auth-app-manager",
                "blurb": ""
          },
          {
                "name": "OrderStatus",
                "id": "order-status",
                "blurb": ""
          },
          {
                "name": "ParentalDashboard",
                "id": "parental-dashboard",
                "blurb": ""
          },
          {
                "name": "ParticleField",
                "id": "particle-field",
                "blurb": ""
          },
          {
                "name": "PfpUpload",
                "id": "pfp-upload",
                "blurb": ""
          },
          {
                "name": "PlaylistCard",
                "id": "playlist-card",
                "blurb": ""
          },
          {
                "name": "PlaylistEditor",
                "id": "playlist-editor",
                "blurb": ""
          },
          {
                "name": "PlaylistView",
                "id": "playlist-view",
                "blurb": ""
          },
          {
                "name": "PluginCard",
                "id": "plugin-card",
                "blurb": ""
          },
          {
                "name": "PluginMarketplace",
                "id": "plugin-marketplace",
                "blurb": ""
          },
          {
                "name": "PluginSettings",
                "id": "plugin-settings",
                "blurb": ""
          },
          {
                "name": "PngtuberManager",
                "id": "pngtuber-manager",
                "blurb": ""
          },
          {
                "name": "PngtuberRenderer",
                "id": "pngtuber-renderer",
                "blurb": ""
          },
          {
                "name": "PngtuberSetup",
                "id": "pngtuber-setup",
                "blurb": ""
          },
          {
                "name": "PopupOverlay",
                "id": "popup-overlay",
                "blurb": ""
          },
          {
                "name": "PostCreator",
                "id": "post-creator",
                "blurb": ""
          },
          {
                "name": "PostCreatorPopover",
                "id": "post-creator-popover",
                "blurb": ""
          },
          {
                "name": "PostList",
                "id": "post-list",
                "blurb": ""
          },
          {
                "name": "PredictionWidget",
                "id": "prediction-widget",
                "blurb": ""
          },
          {
                "name": "PrestigeButton",
                "id": "prestige-button",
                "blurb": ""
          },
          {
                "name": "ProfileMusicPlayer",
                "id": "profile-music-player",
                "blurb": ""
          },
          {
                "name": "ProfilePicture",
                "id": "profile-picture",
                "blurb": ""
          },
          {
                "name": "ProfilePopover",
                "id": "profile-popover",
                "blurb": ""
          },
          {
                "name": "PromoteDialog",
                "id": "promote-dialog",
                "blurb": ""
          },
          {
                "name": "QuizBuilder",
                "id": "quiz-builder",
                "blurb": ""
          },
          {
                "name": "QuizLeaderboard",
                "id": "quiz-leaderboard",
                "blurb": ""
          },
          {
                "name": "QuizPlayer",
                "id": "quiz-player",
                "blurb": ""
          },
          {
                "name": "QuizResults",
                "id": "quiz-results",
                "blurb": ""
          },
          {
                "name": "QuoteComposer",
                "id": "quote-composer",
                "blurb": ""
          },
          {
                "name": "RaidButton",
                "id": "raid-button",
                "blurb": ""
          },
          {
                "name": "ReactionsOverlay",
                "id": "reactions-overlay",
                "blurb": ""
          },
          {
                "name": "RecurringPostEditor",
                "id": "recurring-post-editor",
                "blurb": ""
          },
          {
                "name": "ReelEditor",
                "id": "reel-editor",
                "blurb": ""
          },
          {
                "name": "ReelFeed",
                "id": "reel-feed",
                "blurb": ""
          },
          {
                "name": "ReelOverlay",
                "id": "reel-overlay",
                "blurb": ""
          },
          {
                "name": "ReelPlayer",
                "id": "reel-player",
                "blurb": ""
          },
          {
                "name": "RelatedPostsSidebar",
                "id": "related-posts-sidebar",
                "blurb": ""
          },
          {
                "name": "RepostButton",
                "id": "repost-button",
                "blurb": ""
          },
          {
                "name": "RepostChainView",
                "id": "repost-chain-view",
                "blurb": ""
          },
          {
                "name": "RevenueChart",
                "id": "revenue-chart",
                "blurb": ""
          },
          {
                "name": "RssFeedLink",
                "id": "rss-feed-link",
                "blurb": ""
          },
          {
                "name": "RsvpButton",
                "id": "rsvp-button",
                "blurb": ""
          },
          {
                "name": "ScheduleCalendar",
                "id": "schedule-calendar",
                "blurb": ""
          },
          {
                "name": "SchedulePicker",
                "id": "schedule-picker",
                "blurb": ""
          },
          {
                "name": "Screensaver",
                "id": "screensaver",
                "blurb": ""
          },
          {
                "name": "ScreenTimeReminder",
                "id": "screen-time-reminder",
                "blurb": ""
          },
          {
                "name": "SellerRating",
                "id": "seller-rating",
                "blurb": ""
          },
          {
                "name": "ShareButton",
                "id": "share-button",
                "blurb": ""
          },
          {
                "name": "ShareCard",
                "id": "share-card",
                "blurb": ""
          },
          {
                "name": "SharePopover",
                "id": "share-popover",
                "blurb": ""
          },
          {
                "name": "ShowTos",
                "id": "show-tos",
                "blurb": ""
          },
          {
                "name": "Skeleton",
                "id": "skeleton",
                "blurb": ""
          },
          {
                "name": "SkeletonCard",
                "id": "skeleton-card",
                "blurb": ""
          },
          {
                "name": "SkeletonList",
                "id": "skeleton-list",
                "blurb": ""
          },
          {
                "name": "Snowfall",
                "id": "snowfall",
                "blurb": ""
          },
          {
                "name": "SoundboardPanel",
                "id": "soundboard-panel",
                "blurb": ""
          },
          {
                "name": "SoundPicker",
                "id": "sound-picker",
                "blurb": ""
          },
          {
                "name": "Spinner",
                "id": "spinner",
                "blurb": ""
          },
          {
                "name": "StageChannel",
                "id": "stage-channel",
                "blurb": ""
          },
          {
                "name": "Static",
                "id": "static",
                "blurb": ""
          },
          {
                "name": "StickerPicker",
                "id": "sticker-picker",
                "blurb": ""
          },
          {
                "name": "StoryCreator",
                "id": "story-creator",
                "blurb": ""
          },
          {
                "name": "StoryHighlightEditor",
                "id": "story-highlight-editor",
                "blurb": ""
          },
          {
                "name": "StoryRing",
                "id": "story-ring",
                "blurb": ""
          },
          {
                "name": "StoryTray",
                "id": "story-tray",
                "blurb": ""
          },
          {
                "name": "StoryViewer",
                "id": "story-viewer",
                "blurb": ""
          },
          {
                "name": "StreakCalendar",
                "id": "streak-calendar",
                "blurb": ""
          },
          {
                "name": "StreakDisplay",
                "id": "streak-display",
                "blurb": ""
          },
          {
                "name": "StreakFreezeShop",
                "id": "streak-freeze-shop",
                "blurb": ""
          },
          {
                "name": "StreakLeaderboard",
                "id": "streak-leaderboard",
                "blurb": ""
          },
          {
                "name": "StreakMilestone",
                "id": "streak-milestone",
                "blurb": ""
          },
          {
                "name": "StreamChat",
                "id": "stream-chat",
                "blurb": ""
          },
          {
                "name": "StreamReactionBar",
                "id": "stream-reaction-bar",
                "blurb": ""
          },
          {
                "name": "StreamSetup",
                "id": "stream-setup",
                "blurb": ""
          },
          {
                "name": "StudioPanel",
                "id": "studio-panel",
                "blurb": ""
          },
          {
                "name": "SubscribeButton",
                "id": "subscribe-button",
                "blurb": ""
          },
          {
                "name": "SubscriberBadge",
                "id": "subscriber-badge",
                "blurb": ""
          },
          {
                "name": "SubscriberOnlyGate",
                "id": "subscriber-only-gate",
                "blurb": ""
          },
          {
                "name": "SubscriptionTierCard",
                "id": "subscription-tier-card",
                "blurb": ""
          },
          {
                "name": "SuperReactionPicker",
                "id": "super-reaction-picker",
                "blurb": ""
          },
          {
                "name": "TermsOfService",
                "id": "terms-of-service",
                "blurb": ""
          },
          {
                "name": "Texticle",
                "id": "texticle",
                "blurb": ""
          },
          {
                "name": "ThreadPanel",
                "id": "thread-panel",
                "blurb": ""
          },
          {
                "name": "Thumbnail",
                "id": "thumbnail",
                "blurb": ""
          },
          {
                "name": "TimeLimitWarning",
                "id": "time-limit-warning",
                "blurb": ""
          },
          {
                "name": "TimestampComment",
                "id": "timestamp-comment",
                "blurb": ""
          },
          {
                "name": "TimestampCommentList",
                "id": "timestamp-comment-list",
                "blurb": ""
          },
          {
                "name": "TimestampHeatmap",
                "id": "timestamp-heatmap",
                "blurb": ""
          },
          {
                "name": "TimestampInput",
                "id": "timestamp-input",
                "blurb": ""
          },
          {
                "name": "TipAnimation",
                "id": "tip-animation",
                "blurb": ""
          },
          {
                "name": "TipButton",
                "id": "tip-button",
                "blurb": ""
          },
          {
                "name": "TipDialog",
                "id": "tip-dialog",
                "blurb": ""
          },
          {
                "name": "TipJarWidget",
                "id": "tip-jar-widget",
                "blurb": ""
          },
          {
                "name": "Toast",
                "id": "toast",
                "blurb": ""
          },
          {
                "name": "ToastContainer",
                "id": "toast-container",
                "blurb": ""
          },
          {
                "name": "TopicCard",
                "id": "topic-card",
                "blurb": ""
          },
          {
                "name": "TopicFeed",
                "id": "topic-feed",
                "blurb": ""
          },
          {
                "name": "TopicSuggestions",
                "id": "topic-suggestions",
                "blurb": ""
          },
          {
                "name": "TournamentBracket",
                "id": "tournament-bracket",
                "blurb": ""
          },
          {
                "name": "TrendingHashtags",
                "id": "trending-hashtags",
                "blurb": ""
          },
          {
                "name": "TtfBoard",
                "id": "ttf-board",
                "blurb": ""
          },
          {
                "name": "TtfBotList",
                "id": "ttf-bot-list",
                "blurb": ""
          },
          {
                "name": "TtfReplayViewer",
                "id": "ttf-replay-viewer",
                "blurb": ""
          },
          {
                "name": "Tv",
                "id": "tv",
                "blurb": ""
          },
          {
                "name": "TvBox",
                "id": "tv-box",
                "blurb": ""
          },
          {
                "name": "TvFrame",
                "id": "tv-frame",
                "blurb": ""
          },
          {
                "name": "TwoFactorSetup",
                "id": "two-factor-setup",
                "blurb": ""
          },
          {
                "name": "TwoFactorStatus",
                "id": "two-factor-status",
                "blurb": ""
          },
          {
                "name": "UserList",
                "id": "user-list",
                "blurb": ""
          },
          {
                "name": "UserOtpLoginForm",
                "id": "user-otp-login-form",
                "blurb": ""
          },
          {
                "name": "UserOtpRegistrationForm",
                "id": "user-otp-registration-form",
                "blurb": ""
          },
          {
                "name": "VerificationFlow",
                "id": "verification-flow",
                "blurb": ""
          },
          {
                "name": "VerificationStatus",
                "id": "verification-status",
                "blurb": ""
          },
          {
                "name": "VerifiedBadge",
                "id": "verified-badge",
                "blurb": ""
          },
          {
                "name": "VideoList",
                "id": "video-list",
                "blurb": ""
          },
          {
                "name": "VideoPlayer",
                "id": "video-player",
                "blurb": ""
          },
          {
                "name": "VideoPopout",
                "id": "video-popout",
                "blurb": ""
          },
          {
                "name": "ViewerCounter",
                "id": "viewer-counter",
                "blurb": ""
          },
          {
                "name": "VoiceActivityIndicator",
                "id": "voice-activity-indicator",
                "blurb": ""
          },
          {
                "name": "VoiceChannelBar",
                "id": "voice-channel-bar",
                "blurb": ""
          },
          {
                "name": "VoiceChannelList",
                "id": "voice-channel-list",
                "blurb": ""
          },
          {
                "name": "VoiceMessageBubble",
                "id": "voice-message-bubble",
                "blurb": ""
          },
          {
                "name": "VoiceParticipantList",
                "id": "voice-participant-list",
                "blurb": ""
          },
          {
                "name": "WebhookManager",
                "id": "webhook-manager",
                "blurb": ""
          },
          {
                "name": "WikiPageView",
                "id": "wiki-page-view",
                "blurb": ""
          },
          {
                "name": "WikiSidebar",
                "id": "wiki-sidebar",
                "blurb": ""
          },
          {
                "name": "WinPanel",
                "id": "win-panel",
                "blurb": ""
          },
          {
                "name": "XpBar",
                "id": "xp-bar",
                "blurb": ""
          },
          {
                "name": "XpGainToast",
                "id": "xp-gain-toast",
                "blurb": ""
          },
          {
                "name": "YouTubeEmbed",
                "id": "you-tube-embed",
                "blurb": ""
          }
    ],
  },
];

export const allItems: CatalogItem[] = catalog.flatMap(g => g.items);
