// vendored verbatim @cloudscape-design/components/drawer
export default {
  "root": "awsui_root_1sxt8_1cneo_193",
  "drawer": "awsui_drawer_1sxt8_1cneo_197",
  "has-close-action": "awsui_has-close-action_1sxt8_1cneo_230",
  "position-absolute": "awsui_position-absolute_1sxt8_1cneo_233",
  "position-sticky": "awsui_position-sticky_1sxt8_1cneo_233",
  "position-fixed": "awsui_position-fixed_1sxt8_1cneo_233",
  "with-footer": "awsui_with-footer_1sxt8_1cneo_236",
  "position-static": "awsui_position-static_1sxt8_1cneo_240",
  "content": "awsui_content_1sxt8_1cneo_243",
  "header": "awsui_header_1sxt8_1cneo_271",
  "hide-close-action": "awsui_hide-close-action_1sxt8_1cneo_287",
  "with-additional-action": "awsui_with-additional-action_1sxt8_1cneo_291",
  "with-runtime-context": "awsui_with-runtime-context_1sxt8_1cneo_299",
  "with-toolbar": "awsui_with-toolbar_1sxt8_1cneo_302",
  "header-actions": "awsui_header-actions_1sxt8_1cneo_321",
  "close-action": "awsui_close-action_1sxt8_1cneo_327",
  "content-with-paddings": "awsui_content-with-paddings_1sxt8_1cneo_333",
  "footer": "awsui_footer_1sxt8_1cneo_340",
  "is-sticky": "awsui_is-sticky_1sxt8_1cneo_346",
  "test-utils-drawer-content": "awsui_test-utils-drawer-content_1sxt8_1cneo_354",
  "hidden": "awsui_hidden_1sxt8_1cneo_358",
  "focus-trap": "awsui_focus-trap_1sxt8_1cneo_362",
  "backdrop": "awsui_backdrop_1sxt8_1cneo_366",
  "backdrop-fixed": "awsui_backdrop-fixed_1sxt8_1cneo_370",
  "backdrop-absolute": "awsui_backdrop-absolute_1sxt8_1cneo_373"
};
